import { useEffect, useMemo, useState } from 'react';
import Plot from 'react-plotly.js';
import { Search, SlidersHorizontal } from 'lucide-react';
import { fetchNews, type NewsItem } from '../services/api';
import { Card, CardContent, CardHeader, CardTitle } from '../components/common/Card';
import { Skeleton } from '../components/common/Skeleton';

export function News(){
  const[data,setData]=useState<NewsItem[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[query,setQuery]=useState('');const[filter,setFilter]=useState<'all'|'positive'|'neutral'|'negative'>('all');const[page,setPage]=useState(1);const perPage=12;
  const load=()=>{setLoading(true);setError(null);fetchNews().then(setData).catch(e=>setError(e instanceof Error?e.message:'Failed to load sentiment data.')).finally(()=>setLoading(false));};
  useEffect(()=>{load();window.addEventListener('refresh_data',load);return()=>window.removeEventListener('refresh_data',load)},[]);
  useEffect(()=>setPage(1),[query,filter]);
  const filtered=useMemo(()=>data.filter(x=>x.headline.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||x.sentiment===filter)),[data,query,filter]);
  const pages=Math.max(1,Math.ceil(filtered.length/perPage));const shown=filtered.slice((page-1)*perPage,page*perPage);
  const counts={positive:data.filter(x=>x.sentiment==='positive').length,negative:data.filter(x=>x.sentiment==='negative').length,neutral:data.filter(x=>x.sentiment==='neutral').length};
  const daily=[...new Set(data.map(x=>x.date))].sort();const dailyScore=daily.map(date=>{const rows=data.filter(x=>x.date===date);return rows.reduce((s,x)=>s+x.sentiment_score,0)/rows.length;});
  if(loading)return <div className="space-y-6"><Skeleton className="h-48"/><Skeleton className="h-[360px]"/><Skeleton className="h-[600px]"/></div>;
  if(error)return <Card className="border-negative/20 bg-negative/5"><CardContent className="p-10 text-center"><h3 className="font-semibold">Sentiment data unavailable</h3><p className="mt-2 text-sm text-muted">{error}</p><button onClick={load} className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold">Retry</button></CardContent></Card>;
  return <div className="mx-auto max-w-[1500px] space-y-6 animate-in fade-in duration-500">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.18em] text-primary">News intelligence</p><h2 className="text-2xl font-bold">AI Sentiment</h2><p className="mt-1 text-sm text-muted">LLM-derived labels and scores for the supplied financial headlines.</p></div><span className="w-max rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-xs text-primary">Demonstration / synthetic dataset</span></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total headlines" value={data.length.toString()}/><Stat label="Positive" value={counts.positive.toString()} tone="positive"/><Stat label="Neutral" value={counts.neutral.toString()}/><Stat label="Negative" value={counts.negative.toString()} tone="negative"/></div>
    <Card><CardHeader><CardTitle>Daily sentiment trend</CardTitle></CardHeader><CardContent className="h-[320px] p-0"><Plot data={[{x:daily,y:dailyScore,type:'scatter',mode:'lines+markers',line:{color:'#3B82F6',width:2},marker:{size:5}}]} layout={{autosize:true,margin:{l:50,r:20,t:15,b:45},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#94A3B8',family:'Inter',size:11},xaxis:{type:'date',gridcolor:'rgba(255,255,255,.05)',nticks:8},yaxis:{gridcolor:'rgba(255,255,255,.05)',zerolinecolor:'rgba(255,255,255,.2)',range:[-1,1]}}} useResizeHandler style={{width:'100%',height:'100%'}} config={{displayModeBar:false}}/></CardContent></Card>
    <Card><CardHeader className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><CardTitle className="flex items-center gap-2"><SlidersHorizontal size={18} className="text-primary"/> Analyzed headlines</CardTitle><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search size={15} className="absolute left-3 top-2.5 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search headlines…" className="w-full rounded-lg border border-white/10 bg-background py-2 pl-9 pr-3 text-sm outline-none focus:border-primary sm:w-64"/></label><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} className="rounded-lg border border-white/10 bg-background px-3 py-2 text-sm text-white outline-none"><option value="all">All sentiments</option><option value="positive">Positive</option><option value="neutral">Neutral</option><option value="negative">Negative</option></select></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="border-b border-white/5 text-left text-xs uppercase tracking-wider text-muted"><tr><th className="pb-3">Date</th><th className="w-1/2 pb-3">Headline</th><th className="pb-3 text-center">Sentiment</th><th className="pb-3 text-right">Score</th><th className="pb-3 text-right">Confidence</th></tr></thead><tbody className="divide-y divide-white/5">{shown.length?shown.map((item,i)=><tr key={`${item.date}-${i}`} className="hover:bg-white/[.025]"><td className="py-4 align-top text-muted">{item.date}</td><td className="py-4 pr-6 align-top leading-relaxed">{item.headline}</td><td className="py-4 text-center align-top"><Badge sentiment={item.sentiment}/></td><td className={`py-4 text-right font-semibold align-top ${item.sentiment_score>0?'text-positive':item.sentiment_score<0?'text-negative':''}`}>{item.sentiment_score>0?'+':''}{item.sentiment_score.toFixed(2)}</td><td className="py-4 text-right text-muted align-top">{(item.sentiment_confidence*100).toFixed(0)}%</td></tr>):<tr><td colSpan={5} className="py-12 text-center text-muted">No headlines match the selected filters.</td></tr>}</tbody></table></div>
    {pages>1&&<div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4"><p className="text-xs text-muted">Showing {filtered.length?((page-1)*perPage+1):0}–{Math.min(page*perPage,filtered.length)} of {filtered.length}</p><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border border-white/10 bg-surface px-3 py-1.5 text-xs disabled:opacity-40">Previous</button><button disabled={page===pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border border-white/10 bg-surface px-3 py-1.5 text-xs disabled:opacity-40">Next</button></div></div>}
    </CardContent></Card>
  </div>;
}
function Stat({label,value,tone}:{label:string;value:string;tone?:'positive'|'negative'}){return <Card><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className={`mt-2 text-3xl font-bold ${tone==='positive'?'text-positive':tone==='negative'?'text-negative':''}`}>{value}</p></CardContent></Card>}
function Badge({sentiment}:{sentiment:NewsItem['sentiment']}){return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${sentiment==='positive'?'border-positive/20 bg-positive/10 text-positive':sentiment==='negative'?'border-negative/20 bg-negative/10 text-negative':'border-white/10 bg-white/5 text-muted'}`}>{sentiment}</span>}
